### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ibbikhan879819** [BoicCodes/hCaptcha-solver#1]
DevTools listening on ws://127.0.0.1:50070/devtools/browser/27de4cac-e56f-4c68-a20f-bc687fc7a4c6
Traceback (most recent call last):
  File "D:\python learning\New folder (2)\hCaptcha-Solver-master\main.py", line 101, in <module>
    main.start()
  File "D:\python learning\New folder (2)\hCaptcha-Solver-master\main.py", line 62, in start
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "checkbox"))).click()
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by ibbikhan879819** [comment]
i am new in programming, but i need to bypass hcaptcha in www.dropz.xyz website, can u please help me

**Comment by JokersCat** [comment]
Do you found a solution?
